export const ActionTypes = {
    SET_POSTS : "SET_POSTS",
    SELECTED_POST : "SELECTED_POST",
    SET_POST_COMMENTS : "SET_POST_COMMENTS",
    REMOVE_SELECTED_POST : "REMOVE_SELECTED_POST",
    EDIT_SELECTED_POST : "EDIT_SELECTED_POST",
    ADD_POST : "ADD_POST",
    CLEAR_POST_COMMENTS: "CLEAR_POST_COMMENTS"
}